apiVersion: v1
kind: Service
metadata:
  labels:
    app: openlab-rest
  name: openlab-rest
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: openlab-rest
  type: ClusterIP
status:
  loadBalancer: {}
